spring.application.name=Deception
spring.datasource.url=jdbc:mysql://localhost:3306/deception
spring.datasource.username=root
spring.datasource.password=Quang@@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true